/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "GladeCalls.h"
#include "GladeGui.h"
#include "GladeFuncs.h"

GtkWidget*
create_MainWindow (void)
{
  GtkWidget *MainWindow;
  GtkWidget *vbox1;
  GtkWidget *menubar1;
  GtkWidget *item1;
  GtkWidget *item1_menu;
  GtkAccelGroup *item1_menu_accels;
  GtkWidget *RunCd;
  GtkWidget *RunCdBiois;
  GtkWidget *Run_Exe;
  GtkWidget *separator2;
  GtkWidget *states1;
  GtkWidget *states1_menu;
  GtkAccelGroup *states1_menu_accels;
  GtkWidget *load1;
  GtkWidget *load1_menu;
  GtkAccelGroup *load1_menu_accels;
  GtkWidget *GtkMenuItem_LoadSlot1;
  GtkWidget *GtkMenuItem_LoadSlot2;
  GtkWidget *GtkMenuItem_LoadSlot3;
  GtkWidget *GtkMenuItem_LoadSlot4;
  GtkWidget *GtkMenuItem_LoadSlot5;
  GtkWidget *other1;
  GtkWidget *save1;
  GtkWidget *save1_menu;
  GtkAccelGroup *save1_menu_accels;
  GtkWidget *GtkMenuItem_SaveSlot1;
  GtkWidget *GtkMenuItem_SaveSlot2;
  GtkWidget *GtkMenuItem_SaveSlot3;
  GtkWidget *GtkMenuItem_SaveSlot4;
  GtkWidget *GtkMenuItem_SaveSlot5;
  GtkWidget *other2;
  GtkWidget *separator5;
  GtkWidget *exit2;
  GtkWidget *emulator1;
  GtkWidget *emulator1_menu;
  GtkAccelGroup *emulator1_menu_accels;
  GtkWidget *run1;
  GtkWidget *reset1;
  GtkWidget *configuration1;
  GtkWidget *configuration1_menu;
  GtkAccelGroup *configuration1_menu_accels;
  GtkWidget *plugins___bios1;
  GtkWidget *separator3;
  GtkWidget *graphics1;
  GtkWidget *sound1;
  GtkWidget *cd_rom1;
  GtkWidget *controllers1;
  GtkWidget *separator4;
  GtkWidget *netplay1;
  GtkWidget *separator6;
  GtkWidget *cpu1;
  GtkWidget *memory_cards1;
  GtkWidget *GtkMenuItem_Language;
  GtkWidget *help1;
  GtkWidget *help1_menu;
  GtkAccelGroup *help1_menu_accels;
  GtkWidget *about_pcsx1;

  MainWindow = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_object_set_data (GTK_OBJECT (MainWindow), "MainWindow", MainWindow);
  gtk_widget_set_usize (MainWindow, 350, 200);
  gtk_window_set_title (GTK_WINDOW (MainWindow), _("PCSX"));
  gtk_window_set_position (GTK_WINDOW (MainWindow), GTK_WIN_POS_CENTER);
  gtk_window_set_policy (GTK_WINDOW (MainWindow), FALSE, FALSE, FALSE);

  vbox1 = gtk_vbox_new (FALSE, 0);
  gtk_widget_ref (vbox1);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "vbox1", vbox1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox1);
  gtk_container_add (GTK_CONTAINER (MainWindow), vbox1);

  menubar1 = gtk_menu_bar_new ();
  gtk_widget_ref (menubar1);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "menubar1", menubar1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (menubar1);
  gtk_box_pack_start (GTK_BOX (vbox1), menubar1, FALSE, FALSE, 0);

  item1 = gtk_menu_item_new_with_label (_("File"));
  gtk_widget_ref (item1);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "item1", item1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (item1);
  gtk_container_add (GTK_CONTAINER (menubar1), item1);

  item1_menu = gtk_menu_new ();
  gtk_widget_ref (item1_menu);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "item1_menu", item1_menu,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (item1), item1_menu);
  item1_menu_accels = gtk_menu_ensure_uline_accel_group (GTK_MENU (item1_menu));

  RunCd = gtk_menu_item_new_with_label (_("Run Cd"));
  gtk_widget_ref (RunCd);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "RunCd", RunCd,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (RunCd);
  gtk_container_add (GTK_CONTAINER (item1_menu), RunCd);

  RunCdBiois = gtk_menu_item_new_with_label (_("Run Cd Through Bios"));
  gtk_widget_ref (RunCdBiois);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "RunCdBiois", RunCdBiois,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (RunCdBiois);
  gtk_container_add (GTK_CONTAINER (item1_menu), RunCdBiois);

  Run_Exe = gtk_menu_item_new_with_label (_("Run Exe"));
  gtk_widget_ref (Run_Exe);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "Run_Exe", Run_Exe,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (Run_Exe);
  gtk_container_add (GTK_CONTAINER (item1_menu), Run_Exe);

  separator2 = gtk_menu_item_new ();
  gtk_widget_ref (separator2);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "separator2", separator2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (separator2);
  gtk_container_add (GTK_CONTAINER (item1_menu), separator2);
  gtk_widget_set_sensitive (separator2, FALSE);

  states1 = gtk_menu_item_new_with_label (_("States"));
  gtk_widget_ref (states1);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "states1", states1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (states1);
  gtk_container_add (GTK_CONTAINER (item1_menu), states1);

  states1_menu = gtk_menu_new ();
  gtk_widget_ref (states1_menu);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "states1_menu", states1_menu,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (states1), states1_menu);
  states1_menu_accels = gtk_menu_ensure_uline_accel_group (GTK_MENU (states1_menu));

  load1 = gtk_menu_item_new_with_label (_("Load"));
  gtk_widget_ref (load1);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "load1", load1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (load1);
  gtk_container_add (GTK_CONTAINER (states1_menu), load1);

  load1_menu = gtk_menu_new ();
  gtk_widget_ref (load1_menu);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "load1_menu", load1_menu,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (load1), load1_menu);
  load1_menu_accels = gtk_menu_ensure_uline_accel_group (GTK_MENU (load1_menu));

  GtkMenuItem_LoadSlot1 = gtk_menu_item_new_with_label (_("Slot 1"));
  gtk_widget_ref (GtkMenuItem_LoadSlot1);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "GtkMenuItem_LoadSlot1", GtkMenuItem_LoadSlot1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (GtkMenuItem_LoadSlot1);
  gtk_container_add (GTK_CONTAINER (load1_menu), GtkMenuItem_LoadSlot1);

  GtkMenuItem_LoadSlot2 = gtk_menu_item_new_with_label (_("Slot 2"));
  gtk_widget_ref (GtkMenuItem_LoadSlot2);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "GtkMenuItem_LoadSlot2", GtkMenuItem_LoadSlot2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (GtkMenuItem_LoadSlot2);
  gtk_container_add (GTK_CONTAINER (load1_menu), GtkMenuItem_LoadSlot2);

  GtkMenuItem_LoadSlot3 = gtk_menu_item_new_with_label (_("Slot 3"));
  gtk_widget_ref (GtkMenuItem_LoadSlot3);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "GtkMenuItem_LoadSlot3", GtkMenuItem_LoadSlot3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (GtkMenuItem_LoadSlot3);
  gtk_container_add (GTK_CONTAINER (load1_menu), GtkMenuItem_LoadSlot3);

  GtkMenuItem_LoadSlot4 = gtk_menu_item_new_with_label (_("Slot 4"));
  gtk_widget_ref (GtkMenuItem_LoadSlot4);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "GtkMenuItem_LoadSlot4", GtkMenuItem_LoadSlot4,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (GtkMenuItem_LoadSlot4);
  gtk_container_add (GTK_CONTAINER (load1_menu), GtkMenuItem_LoadSlot4);

  GtkMenuItem_LoadSlot5 = gtk_menu_item_new_with_label (_("Slot 5"));
  gtk_widget_ref (GtkMenuItem_LoadSlot5);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "GtkMenuItem_LoadSlot5", GtkMenuItem_LoadSlot5,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (GtkMenuItem_LoadSlot5);
  gtk_container_add (GTK_CONTAINER (load1_menu), GtkMenuItem_LoadSlot5);

  other1 = gtk_menu_item_new_with_label (_("Other..."));
  gtk_widget_ref (other1);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "other1", other1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (other1);
  gtk_container_add (GTK_CONTAINER (load1_menu), other1);

  save1 = gtk_menu_item_new_with_label (_("Save"));
  gtk_widget_ref (save1);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "save1", save1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (save1);
  gtk_container_add (GTK_CONTAINER (states1_menu), save1);

  save1_menu = gtk_menu_new ();
  gtk_widget_ref (save1_menu);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "save1_menu", save1_menu,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (save1), save1_menu);
  save1_menu_accels = gtk_menu_ensure_uline_accel_group (GTK_MENU (save1_menu));

  GtkMenuItem_SaveSlot1 = gtk_menu_item_new_with_label (_("Slot 1"));
  gtk_widget_ref (GtkMenuItem_SaveSlot1);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "GtkMenuItem_SaveSlot1", GtkMenuItem_SaveSlot1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (GtkMenuItem_SaveSlot1);
  gtk_container_add (GTK_CONTAINER (save1_menu), GtkMenuItem_SaveSlot1);

  GtkMenuItem_SaveSlot2 = gtk_menu_item_new_with_label (_("Slot 2"));
  gtk_widget_ref (GtkMenuItem_SaveSlot2);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "GtkMenuItem_SaveSlot2", GtkMenuItem_SaveSlot2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (GtkMenuItem_SaveSlot2);
  gtk_container_add (GTK_CONTAINER (save1_menu), GtkMenuItem_SaveSlot2);

  GtkMenuItem_SaveSlot3 = gtk_menu_item_new_with_label (_("Slot 3"));
  gtk_widget_ref (GtkMenuItem_SaveSlot3);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "GtkMenuItem_SaveSlot3", GtkMenuItem_SaveSlot3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (GtkMenuItem_SaveSlot3);
  gtk_container_add (GTK_CONTAINER (save1_menu), GtkMenuItem_SaveSlot3);

  GtkMenuItem_SaveSlot4 = gtk_menu_item_new_with_label (_("Slot 4"));
  gtk_widget_ref (GtkMenuItem_SaveSlot4);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "GtkMenuItem_SaveSlot4", GtkMenuItem_SaveSlot4,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (GtkMenuItem_SaveSlot4);
  gtk_container_add (GTK_CONTAINER (save1_menu), GtkMenuItem_SaveSlot4);

  GtkMenuItem_SaveSlot5 = gtk_menu_item_new_with_label (_("Slot 5"));
  gtk_widget_ref (GtkMenuItem_SaveSlot5);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "GtkMenuItem_SaveSlot5", GtkMenuItem_SaveSlot5,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (GtkMenuItem_SaveSlot5);
  gtk_container_add (GTK_CONTAINER (save1_menu), GtkMenuItem_SaveSlot5);

  other2 = gtk_menu_item_new_with_label (_("Other..."));
  gtk_widget_ref (other2);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "other2", other2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (other2);
  gtk_container_add (GTK_CONTAINER (save1_menu), other2);

  separator5 = gtk_menu_item_new ();
  gtk_widget_ref (separator5);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "separator5", separator5,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (separator5);
  gtk_container_add (GTK_CONTAINER (item1_menu), separator5);
  gtk_widget_set_sensitive (separator5, FALSE);

  exit2 = gtk_menu_item_new_with_label (_("Exit"));
  gtk_widget_ref (exit2);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "exit2", exit2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (exit2);
  gtk_container_add (GTK_CONTAINER (item1_menu), exit2);

  emulator1 = gtk_menu_item_new_with_label (_("Emulator"));
  gtk_widget_ref (emulator1);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "emulator1", emulator1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (emulator1);
  gtk_container_add (GTK_CONTAINER (menubar1), emulator1);

  emulator1_menu = gtk_menu_new ();
  gtk_widget_ref (emulator1_menu);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "emulator1_menu", emulator1_menu,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (emulator1), emulator1_menu);
  emulator1_menu_accels = gtk_menu_ensure_uline_accel_group (GTK_MENU (emulator1_menu));

  run1 = gtk_menu_item_new_with_label (_("Run"));
  gtk_widget_ref (run1);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "run1", run1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (run1);
  gtk_container_add (GTK_CONTAINER (emulator1_menu), run1);

  reset1 = gtk_menu_item_new_with_label (_("Reset"));
  gtk_widget_ref (reset1);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "reset1", reset1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (reset1);
  gtk_container_add (GTK_CONTAINER (emulator1_menu), reset1);

  configuration1 = gtk_menu_item_new_with_label (_("Configuration"));
  gtk_widget_ref (configuration1);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "configuration1", configuration1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (configuration1);
  gtk_container_add (GTK_CONTAINER (menubar1), configuration1);

  configuration1_menu = gtk_menu_new ();
  gtk_widget_ref (configuration1_menu);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "configuration1_menu", configuration1_menu,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (configuration1), configuration1_menu);
  configuration1_menu_accels = gtk_menu_ensure_uline_accel_group (GTK_MENU (configuration1_menu));

  plugins___bios1 = gtk_menu_item_new_with_label (_("Plugins & Bios"));
  gtk_widget_ref (plugins___bios1);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "plugins___bios1", plugins___bios1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (plugins___bios1);
  gtk_container_add (GTK_CONTAINER (configuration1_menu), plugins___bios1);

  separator3 = gtk_menu_item_new ();
  gtk_widget_ref (separator3);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "separator3", separator3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (separator3);
  gtk_container_add (GTK_CONTAINER (configuration1_menu), separator3);
  gtk_widget_set_sensitive (separator3, FALSE);

  graphics1 = gtk_menu_item_new_with_label (_("Graphics"));
  gtk_widget_ref (graphics1);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "graphics1", graphics1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (graphics1);
  gtk_container_add (GTK_CONTAINER (configuration1_menu), graphics1);

  sound1 = gtk_menu_item_new_with_label (_("Sound"));
  gtk_widget_ref (sound1);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "sound1", sound1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (sound1);
  gtk_container_add (GTK_CONTAINER (configuration1_menu), sound1);

  cd_rom1 = gtk_menu_item_new_with_label (_("CD-ROM"));
  gtk_widget_ref (cd_rom1);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "cd_rom1", cd_rom1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (cd_rom1);
  gtk_container_add (GTK_CONTAINER (configuration1_menu), cd_rom1);

  controllers1 = gtk_menu_item_new_with_label (_("Controllers"));
  gtk_widget_ref (controllers1);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "controllers1", controllers1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (controllers1);
  gtk_container_add (GTK_CONTAINER (configuration1_menu), controllers1);

  separator4 = gtk_menu_item_new ();
  gtk_widget_ref (separator4);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "separator4", separator4,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (separator4);
  gtk_container_add (GTK_CONTAINER (configuration1_menu), separator4);
  gtk_widget_set_sensitive (separator4, FALSE);

  netplay1 = gtk_menu_item_new_with_label (_("NetPlay"));
  gtk_widget_ref (netplay1);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "netplay1", netplay1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (netplay1);
  gtk_container_add (GTK_CONTAINER (configuration1_menu), netplay1);

  separator6 = gtk_menu_item_new ();
  gtk_widget_ref (separator6);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "separator6", separator6,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (separator6);
  gtk_container_add (GTK_CONTAINER (configuration1_menu), separator6);
  gtk_widget_set_sensitive (separator6, FALSE);

  cpu1 = gtk_menu_item_new_with_label (_("Cpu"));
  gtk_widget_ref (cpu1);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "cpu1", cpu1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (cpu1);
  gtk_container_add (GTK_CONTAINER (configuration1_menu), cpu1);

  memory_cards1 = gtk_menu_item_new_with_label (_("Memory Cards"));
  gtk_widget_ref (memory_cards1);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "memory_cards1", memory_cards1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (memory_cards1);
  gtk_container_add (GTK_CONTAINER (configuration1_menu), memory_cards1);

  GtkMenuItem_Language = gtk_menu_item_new_with_label (_("Language"));
  gtk_widget_ref (GtkMenuItem_Language);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "GtkMenuItem_Language", GtkMenuItem_Language,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (GtkMenuItem_Language);
  gtk_container_add (GTK_CONTAINER (menubar1), GtkMenuItem_Language);

  help1 = gtk_menu_item_new_with_label (_("Help"));
  gtk_widget_ref (help1);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "help1", help1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (help1);
  gtk_container_add (GTK_CONTAINER (menubar1), help1);

  help1_menu = gtk_menu_new ();
  gtk_widget_ref (help1_menu);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "help1_menu", help1_menu,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (help1), help1_menu);
  help1_menu_accels = gtk_menu_ensure_uline_accel_group (GTK_MENU (help1_menu));

  about_pcsx1 = gtk_menu_item_new_with_label (_("About PCSX"));
  gtk_widget_ref (about_pcsx1);
  gtk_object_set_data_full (GTK_OBJECT (MainWindow), "about_pcsx1", about_pcsx1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (about_pcsx1);
  gtk_container_add (GTK_CONTAINER (help1_menu), about_pcsx1);

  gtk_signal_connect (GTK_OBJECT (MainWindow), "destroy",
                      GTK_SIGNAL_FUNC (OnDestroy),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (RunCd), "activate",
                      GTK_SIGNAL_FUNC (OnFile_RunCd),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (RunCdBiois), "activate",
                      GTK_SIGNAL_FUNC (OnFile_RunCdBios),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (Run_Exe), "activate",
                      GTK_SIGNAL_FUNC (OnFile_RunExe),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (GtkMenuItem_LoadSlot1), "activate",
                      GTK_SIGNAL_FUNC (OnStates_Load1),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (GtkMenuItem_LoadSlot2), "activate",
                      GTK_SIGNAL_FUNC (OnStates_Load2),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (GtkMenuItem_LoadSlot3), "activate",
                      GTK_SIGNAL_FUNC (OnStates_Load3),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (GtkMenuItem_LoadSlot4), "activate",
                      GTK_SIGNAL_FUNC (OnStates_Load4),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (GtkMenuItem_LoadSlot5), "activate",
                      GTK_SIGNAL_FUNC (OnStates_Load5),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (other1), "activate",
                      GTK_SIGNAL_FUNC (OnStates_LoadOther),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (GtkMenuItem_SaveSlot1), "activate",
                      GTK_SIGNAL_FUNC (OnStates_Save1),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (GtkMenuItem_SaveSlot2), "activate",
                      GTK_SIGNAL_FUNC (OnStates_Save2),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (GtkMenuItem_SaveSlot3), "activate",
                      GTK_SIGNAL_FUNC (OnStates_Save3),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (GtkMenuItem_SaveSlot4), "activate",
                      GTK_SIGNAL_FUNC (OnStates_Save4),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (GtkMenuItem_SaveSlot5), "activate",
                      GTK_SIGNAL_FUNC (OnStates_Save5),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (other2), "activate",
                      GTK_SIGNAL_FUNC (OnStates_SaveOther),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (exit2), "activate",
                      GTK_SIGNAL_FUNC (OnFile_Exit),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (run1), "activate",
                      GTK_SIGNAL_FUNC (OnEmu_Run),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (reset1), "activate",
                      GTK_SIGNAL_FUNC (OnEmu_Reset),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (plugins___bios1), "activate",
                      GTK_SIGNAL_FUNC (OnConf_Conf),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (graphics1), "activate",
                      GTK_SIGNAL_FUNC (OnConf_Gpu),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (sound1), "activate",
                      GTK_SIGNAL_FUNC (OnConf_Spu),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (cd_rom1), "activate",
                      GTK_SIGNAL_FUNC (OnConf_Cdr),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (controllers1), "activate",
                      GTK_SIGNAL_FUNC (OnConf_Pads),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (netplay1), "activate",
                      GTK_SIGNAL_FUNC (OnConf_Net),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (cpu1), "activate",
                      GTK_SIGNAL_FUNC (OnConf_Cpu),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (memory_cards1), "activate",
                      GTK_SIGNAL_FUNC (OnConf_Mcds),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (about_pcsx1), "activate",
                      GTK_SIGNAL_FUNC (OnHelp_About),
                      NULL);

  return MainWindow;
}

GtkWidget*
create_AboutDlg (void)
{
  GtkWidget *AboutDlg;
  GtkWidget *vbox2;
  GtkWidget *packer1;
  GtkWidget *hbox1;
  GtkWidget *vbox4;
  GtkWidget *GtkAbout_LabelVersion;
  GtkWidget *frame1;
  GtkWidget *vbox6;
  GtkWidget *GtkAbout_LabelAuthors;
  GtkWidget *pixmap1;
  GtkWidget *frame2;
  GtkWidget *vbox5;
  GtkWidget *GtkAbout_LabelGreets;
  GtkWidget *hbuttonbox1;
  GtkWidget *button1;

  AboutDlg = gtk_window_new (GTK_WINDOW_DIALOG);
  gtk_object_set_data (GTK_OBJECT (AboutDlg), "AboutDlg", AboutDlg);
  gtk_container_set_border_width (GTK_CONTAINER (AboutDlg), 10);
  gtk_window_set_title (GTK_WINDOW (AboutDlg), _("Pcsx About"));
  gtk_window_set_position (GTK_WINDOW (AboutDlg), GTK_WIN_POS_CENTER);

  vbox2 = gtk_vbox_new (FALSE, 0);
  gtk_widget_ref (vbox2);
  gtk_object_set_data_full (GTK_OBJECT (AboutDlg), "vbox2", vbox2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox2);
  gtk_container_add (GTK_CONTAINER (AboutDlg), vbox2);

  packer1 = gtk_packer_new ();
  gtk_widget_ref (packer1);
  gtk_object_set_data_full (GTK_OBJECT (AboutDlg), "packer1", packer1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (packer1);
  gtk_box_pack_start (GTK_BOX (vbox2), packer1, FALSE, FALSE, 0);

  hbox1 = gtk_hbox_new (FALSE, 0);
  gtk_widget_ref (hbox1);
  gtk_object_set_data_full (GTK_OBJECT (AboutDlg), "hbox1", hbox1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox1);
  gtk_box_pack_start (GTK_BOX (vbox2), hbox1, TRUE, TRUE, 0);

  vbox4 = gtk_vbox_new (FALSE, 0);
  gtk_widget_ref (vbox4);
  gtk_object_set_data_full (GTK_OBJECT (AboutDlg), "vbox4", vbox4,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox4);
  gtk_box_pack_start (GTK_BOX (hbox1), vbox4, TRUE, TRUE, 0);

  GtkAbout_LabelVersion = gtk_label_new (_("PCSX\r\nVersion x.x"));
  gtk_widget_ref (GtkAbout_LabelVersion);
  gtk_object_set_data_full (GTK_OBJECT (AboutDlg), "GtkAbout_LabelVersion", GtkAbout_LabelVersion,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (GtkAbout_LabelVersion);
  gtk_box_pack_start (GTK_BOX (vbox4), GtkAbout_LabelVersion, FALSE, FALSE, 0);

  frame1 = gtk_frame_new (NULL);
  gtk_widget_ref (frame1);
  gtk_object_set_data_full (GTK_OBJECT (AboutDlg), "frame1", frame1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (frame1);
  gtk_box_pack_start (GTK_BOX (vbox4), frame1, FALSE, FALSE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (frame1), 5);

  vbox6 = gtk_vbox_new (FALSE, 0);
  gtk_widget_ref (vbox6);
  gtk_object_set_data_full (GTK_OBJECT (AboutDlg), "vbox6", vbox6,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox6);
  gtk_container_add (GTK_CONTAINER (frame1), vbox6);
  gtk_container_set_border_width (GTK_CONTAINER (vbox6), 5);

  GtkAbout_LabelAuthors = gtk_label_new (_("written by..."));
  gtk_widget_ref (GtkAbout_LabelAuthors);
  gtk_object_set_data_full (GTK_OBJECT (AboutDlg), "GtkAbout_LabelAuthors", GtkAbout_LabelAuthors,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (GtkAbout_LabelAuthors);
  gtk_box_pack_start (GTK_BOX (vbox6), GtkAbout_LabelAuthors, FALSE, FALSE, 0);

  pixmap1 = create_pixmap (AboutDlg, "pcsxAbout.xpm");
  gtk_widget_ref (pixmap1);
  gtk_object_set_data_full (GTK_OBJECT (AboutDlg), "pixmap1", pixmap1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (pixmap1);
  gtk_box_pack_start (GTK_BOX (hbox1), pixmap1, TRUE, TRUE, 0);

  frame2 = gtk_frame_new (NULL);
  gtk_widget_ref (frame2);
  gtk_object_set_data_full (GTK_OBJECT (AboutDlg), "frame2", frame2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (frame2);
  gtk_box_pack_start (GTK_BOX (vbox2), frame2, FALSE, FALSE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (frame2), 5);

  vbox5 = gtk_vbox_new (FALSE, 0);
  gtk_widget_ref (vbox5);
  gtk_object_set_data_full (GTK_OBJECT (AboutDlg), "vbox5", vbox5,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox5);
  gtk_container_add (GTK_CONTAINER (frame2), vbox5);
  gtk_container_set_border_width (GTK_CONTAINER (vbox5), 5);

  GtkAbout_LabelGreets = gtk_label_new (_("greets to..."));
  gtk_widget_ref (GtkAbout_LabelGreets);
  gtk_object_set_data_full (GTK_OBJECT (AboutDlg), "GtkAbout_LabelGreets", GtkAbout_LabelGreets,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (GtkAbout_LabelGreets);
  gtk_box_pack_start (GTK_BOX (vbox5), GtkAbout_LabelGreets, FALSE, FALSE, 0);

  hbuttonbox1 = gtk_hbutton_box_new ();
  gtk_widget_ref (hbuttonbox1);
  gtk_object_set_data_full (GTK_OBJECT (AboutDlg), "hbuttonbox1", hbuttonbox1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbuttonbox1);
  gtk_box_pack_start (GTK_BOX (vbox2), hbuttonbox1, TRUE, TRUE, 0);

  button1 = gtk_button_new_with_label (_("Ok"));
  gtk_widget_ref (button1);
  gtk_object_set_data_full (GTK_OBJECT (AboutDlg), "button1", button1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button1);
  gtk_container_add (GTK_CONTAINER (hbuttonbox1), button1);
  GTK_WIDGET_SET_FLAGS (button1, GTK_CAN_DEFAULT);

  gtk_signal_connect (GTK_OBJECT (button1), "clicked",
                      GTK_SIGNAL_FUNC (OnHelpAbout_Ok),
                      NULL);

  return AboutDlg;
}

GtkWidget*
create_ConfDlg (void)
{
  GtkWidget *ConfDlg;
  GtkWidget *vbox12;
  GtkWidget *table2;
  GtkWidget *GtkCombo_Pad1;
  GtkWidget *combo_entry4;
  GtkWidget *GtkCombo_Pad2;
  GtkWidget *combo_entry5;
  GtkWidget *GtkCombo_Cdr;
  GtkWidget *combo_entry6;
  GtkWidget *GtkCombo_Bios;
  GtkWidget *combo_entry7;
  GtkWidget *hbuttonbox5;
  GtkWidget *button6;
  GtkWidget *button7;
  GtkWidget *button8;
  GtkWidget *hbuttonbox6;
  GtkWidget *button9;
  GtkWidget *button10;
  GtkWidget *button11;
  GtkWidget *hbuttonbox7;
  GtkWidget *button12;
  GtkWidget *button13;
  GtkWidget *button14;
  GtkWidget *hbuttonbox8;
  GtkWidget *button15;
  GtkWidget *button16;
  GtkWidget *button17;
  GtkWidget *hbuttonbox9;
  GtkWidget *button18;
  GtkWidget *button19;
  GtkWidget *button20;
  GtkWidget *label2;
  GtkWidget *label1;
  GtkWidget *label3;
  GtkWidget *label5;
  GtkWidget *label6;
  GtkWidget *label4;
  GtkWidget *GtkCombo_Gpu;
  GtkWidget *combo_entry2;
  GtkWidget *GtkCombo_Spu;
  GtkWidget *combo_entry3;
  GtkWidget *hbox5;
  GtkWidget *hbuttonbox11;
  GtkWidget *button22;
  GtkWidget *button23;
  GtkWidget *hbuttonbox10;
  GtkWidget *button4;
  GtkWidget *button25;

  ConfDlg = gtk_window_new (GTK_WINDOW_DIALOG);
  gtk_object_set_data (GTK_OBJECT (ConfDlg), "ConfDlg", ConfDlg);
  gtk_container_set_border_width (GTK_CONTAINER (ConfDlg), 10);
  gtk_window_set_title (GTK_WINDOW (ConfDlg), _("Conf"));
  gtk_window_set_position (GTK_WINDOW (ConfDlg), GTK_WIN_POS_CENTER);

  vbox12 = gtk_vbox_new (FALSE, 0);
  gtk_widget_ref (vbox12);
  gtk_object_set_data_full (GTK_OBJECT (ConfDlg), "vbox12", vbox12,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox12);
  gtk_container_add (GTK_CONTAINER (ConfDlg), vbox12);

  table2 = gtk_table_new (9, 2, FALSE);
  gtk_widget_ref (table2);
  gtk_object_set_data_full (GTK_OBJECT (ConfDlg), "table2", table2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (table2);
  gtk_box_pack_start (GTK_BOX (vbox12), table2, TRUE, TRUE, 0);
  gtk_table_set_col_spacings (GTK_TABLE (table2), 15);

  GtkCombo_Pad1 = gtk_combo_new ();
  gtk_widget_ref (GtkCombo_Pad1);
  gtk_object_set_data_full (GTK_OBJECT (ConfDlg), "GtkCombo_Pad1", GtkCombo_Pad1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (GtkCombo_Pad1);
  gtk_table_attach (GTK_TABLE (table2), GtkCombo_Pad1, 0, 1, 4, 5,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  combo_entry4 = GTK_COMBO (GtkCombo_Pad1)->entry;
  gtk_widget_ref (combo_entry4);
  gtk_object_set_data_full (GTK_OBJECT (ConfDlg), "combo_entry4", combo_entry4,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (combo_entry4);

  GtkCombo_Pad2 = gtk_combo_new ();
  gtk_widget_ref (GtkCombo_Pad2);
  gtk_object_set_data_full (GTK_OBJECT (ConfDlg), "GtkCombo_Pad2", GtkCombo_Pad2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (GtkCombo_Pad2);
  gtk_table_attach (GTK_TABLE (table2), GtkCombo_Pad2, 1, 2, 4, 5,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  combo_entry5 = GTK_COMBO (GtkCombo_Pad2)->entry;
  gtk_widget_ref (combo_entry5);
  gtk_object_set_data_full (GTK_OBJECT (ConfDlg), "combo_entry5", combo_entry5,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (combo_entry5);

  GtkCombo_Cdr = gtk_combo_new ();
  gtk_widget_ref (GtkCombo_Cdr);
  gtk_object_set_data_full (GTK_OBJECT (ConfDlg), "GtkCombo_Cdr", GtkCombo_Cdr,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (GtkCombo_Cdr);
  gtk_table_attach (GTK_TABLE (table2), GtkCombo_Cdr, 0, 1, 7, 8,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  combo_entry6 = GTK_COMBO (GtkCombo_Cdr)->entry;
  gtk_widget_ref (combo_entry6);
  gtk_object_set_data_full (GTK_OBJECT (ConfDlg), "combo_entry6", combo_entry6,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (combo_entry6);

  GtkCombo_Bios = gtk_combo_new ();
  gtk_widget_ref (GtkCombo_Bios);
  gtk_object_set_data_full (GTK_OBJECT (ConfDlg), "GtkCombo_Bios", GtkCombo_Bios,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (GtkCombo_Bios);
  gtk_table_attach (GTK_TABLE (table2), GtkCombo_Bios, 1, 2, 7, 8,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  combo_entry7 = GTK_COMBO (GtkCombo_Bios)->entry;
  gtk_widget_ref (combo_entry7);
  gtk_object_set_data_full (GTK_OBJECT (ConfDlg), "combo_entry7", combo_entry7,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (combo_entry7);

  hbuttonbox5 = gtk_hbutton_box_new ();
  gtk_widget_ref (hbuttonbox5);
  gtk_object_set_data_full (GTK_OBJECT (ConfDlg), "hbuttonbox5", hbuttonbox5,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbuttonbox5);
  gtk_table_attach (GTK_TABLE (table2), hbuttonbox5, 0, 1, 8, 9,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL), 0, 0);
  gtk_button_box_set_spacing (GTK_BUTTON_BOX (hbuttonbox5), 0);

  button6 = gtk_button_new_with_label (_("Configure"));
  gtk_widget_ref (button6);
  gtk_object_set_data_full (GTK_OBJECT (ConfDlg), "button6", button6,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button6);
  gtk_container_add (GTK_CONTAINER (hbuttonbox5), button6);
  GTK_WIDGET_SET_FLAGS (button6, GTK_CAN_DEFAULT);

  button7 = gtk_button_new_with_label (_("Test"));
  gtk_widget_ref (button7);
  gtk_object_set_data_full (GTK_OBJECT (ConfDlg), "button7", button7,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button7);
  gtk_container_add (GTK_CONTAINER (hbuttonbox5), button7);
  GTK_WIDGET_SET_FLAGS (button7, GTK_CAN_DEFAULT);

  button8 = gtk_button_new_with_label (_("About"));
  gtk_widget_ref (button8);
  gtk_object_set_data_full (GTK_OBJECT (ConfDlg), "button8", button8,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button8);
  gtk_container_add (GTK_CONTAINER (hbuttonbox5), button8);
  GTK_WIDGET_SET_FLAGS (button8, GTK_CAN_DEFAULT);

  hbuttonbox6 = gtk_hbutton_box_new ();
  gtk_widget_ref (hbuttonbox6);
  gtk_object_set_data_full (GTK_OBJECT (ConfDlg), "hbuttonbox6", hbuttonbox6,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbuttonbox6);
  gtk_table_attach (GTK_TABLE (table2), hbuttonbox6, 1, 2, 5, 6,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL), 0, 0);
  gtk_button_box_set_spacing (GTK_BUTTON_BOX (hbuttonbox6), 0);

  button9 = gtk_button_new_with_label (_("Configure"));
  gtk_widget_ref (button9);
  gtk_object_set_data_full (GTK_OBJECT (ConfDlg), "button9", button9,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button9);
  gtk_container_add (GTK_CONTAINER (hbuttonbox6), button9);
  GTK_WIDGET_SET_FLAGS (button9, GTK_CAN_DEFAULT);

  button10 = gtk_button_new_with_label (_("Test"));
  gtk_widget_ref (button10);
  gtk_object_set_data_full (GTK_OBJECT (ConfDlg), "button10", button10,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button10);
  gtk_container_add (GTK_CONTAINER (hbuttonbox6), button10);
  GTK_WIDGET_SET_FLAGS (button10, GTK_CAN_DEFAULT);

  button11 = gtk_button_new_with_label (_("About"));
  gtk_widget_ref (button11);
  gtk_object_set_data_full (GTK_OBJECT (ConfDlg), "button11", button11,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button11);
  gtk_container_add (GTK_CONTAINER (hbuttonbox6), button11);
  GTK_WIDGET_SET_FLAGS (button11, GTK_CAN_DEFAULT);

  hbuttonbox7 = gtk_hbutton_box_new ();
  gtk_widget_ref (hbuttonbox7);
  gtk_object_set_data_full (GTK_OBJECT (ConfDlg), "hbuttonbox7", hbuttonbox7,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbuttonbox7);
  gtk_table_attach (GTK_TABLE (table2), hbuttonbox7, 0, 1, 5, 6,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);
  gtk_button_box_set_spacing (GTK_BUTTON_BOX (hbuttonbox7), 0);

  button12 = gtk_button_new_with_label (_("Configure"));
  gtk_widget_ref (button12);
  gtk_object_set_data_full (GTK_OBJECT (ConfDlg), "button12", button12,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button12);
  gtk_container_add (GTK_CONTAINER (hbuttonbox7), button12);
  GTK_WIDGET_SET_FLAGS (button12, GTK_CAN_DEFAULT);

  button13 = gtk_button_new_with_label (_("Test"));
  gtk_widget_ref (button13);
  gtk_object_set_data_full (GTK_OBJECT (ConfDlg), "button13", button13,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button13);
  gtk_container_add (GTK_CONTAINER (hbuttonbox7), button13);
  GTK_WIDGET_SET_FLAGS (button13, GTK_CAN_DEFAULT);

  button14 = gtk_button_new_with_label (_("About"));
  gtk_widget_ref (button14);
  gtk_object_set_data_full (GTK_OBJECT (ConfDlg), "button14", button14,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button14);
  gtk_container_add (GTK_CONTAINER (hbuttonbox7), button14);
  GTK_WIDGET_SET_FLAGS (button14, GTK_CAN_DEFAULT);

  hbuttonbox8 = gtk_hbutton_box_new ();
  gtk_widget_ref (hbuttonbox8);
  gtk_object_set_data_full (GTK_OBJECT (ConfDlg), "hbuttonbox8", hbuttonbox8,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbuttonbox8);
  gtk_table_attach (GTK_TABLE (table2), hbuttonbox8, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL), 0, 0);
  gtk_button_box_set_spacing (GTK_BUTTON_BOX (hbuttonbox8), 0);

  button15 = gtk_button_new_with_label (_("Configure"));
  gtk_widget_ref (button15);
  gtk_object_set_data_full (GTK_OBJECT (ConfDlg), "button15", button15,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button15);
  gtk_container_add (GTK_CONTAINER (hbuttonbox8), button15);
  GTK_WIDGET_SET_FLAGS (button15, GTK_CAN_DEFAULT);

  button16 = gtk_button_new_with_label (_("Test"));
  gtk_widget_ref (button16);
  gtk_object_set_data_full (GTK_OBJECT (ConfDlg), "button16", button16,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button16);
  gtk_container_add (GTK_CONTAINER (hbuttonbox8), button16);
  GTK_WIDGET_SET_FLAGS (button16, GTK_CAN_DEFAULT);

  button17 = gtk_button_new_with_label (_("About"));
  gtk_widget_ref (button17);
  gtk_object_set_data_full (GTK_OBJECT (ConfDlg), "button17", button17,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button17);
  gtk_container_add (GTK_CONTAINER (hbuttonbox8), button17);
  GTK_WIDGET_SET_FLAGS (button17, GTK_CAN_DEFAULT);

  hbuttonbox9 = gtk_hbutton_box_new ();
  gtk_widget_ref (hbuttonbox9);
  gtk_object_set_data_full (GTK_OBJECT (ConfDlg), "hbuttonbox9", hbuttonbox9,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbuttonbox9);
  gtk_table_attach (GTK_TABLE (table2), hbuttonbox9, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);
  gtk_button_box_set_spacing (GTK_BUTTON_BOX (hbuttonbox9), 0);

  button18 = gtk_button_new_with_label (_("Configure"));
  gtk_widget_ref (button18);
  gtk_object_set_data_full (GTK_OBJECT (ConfDlg), "button18", button18,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button18);
  gtk_container_add (GTK_CONTAINER (hbuttonbox9), button18);
  GTK_WIDGET_SET_FLAGS (button18, GTK_CAN_DEFAULT);

  button19 = gtk_button_new_with_label (_("Test"));
  gtk_widget_ref (button19);
  gtk_object_set_data_full (GTK_OBJECT (ConfDlg), "button19", button19,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button19);
  gtk_container_add (GTK_CONTAINER (hbuttonbox9), button19);
  GTK_WIDGET_SET_FLAGS (button19, GTK_CAN_DEFAULT);

  button20 = gtk_button_new_with_label (_("About"));
  gtk_widget_ref (button20);
  gtk_object_set_data_full (GTK_OBJECT (ConfDlg), "button20", button20,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button20);
  gtk_container_add (GTK_CONTAINER (hbuttonbox9), button20);
  GTK_WIDGET_SET_FLAGS (button20, GTK_CAN_DEFAULT);

  label2 = gtk_label_new (_("Sound"));
  gtk_widget_ref (label2);
  gtk_object_set_data_full (GTK_OBJECT (ConfDlg), "label2", label2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label2);
  gtk_table_attach (GTK_TABLE (table2), label2, 1, 2, 0, 1,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label2), 0, 0.5);

  label1 = gtk_label_new (_("Graphics"));
  gtk_widget_ref (label1);
  gtk_object_set_data_full (GTK_OBJECT (ConfDlg), "label1", label1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label1);
  gtk_table_attach (GTK_TABLE (table2), label1, 0, 1, 0, 1,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label1), 0, 0.5);

  label3 = gtk_label_new (_("First Controller"));
  gtk_widget_ref (label3);
  gtk_object_set_data_full (GTK_OBJECT (ConfDlg), "label3", label3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label3);
  gtk_table_attach (GTK_TABLE (table2), label3, 0, 1, 3, 4,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label3), 0, 0.5);

  label5 = gtk_label_new (_("Cdrom"));
  gtk_widget_ref (label5);
  gtk_object_set_data_full (GTK_OBJECT (ConfDlg), "label5", label5,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label5);
  gtk_table_attach (GTK_TABLE (table2), label5, 0, 1, 6, 7,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label5), 0, 0.5);

  label6 = gtk_label_new (_("Bios"));
  gtk_widget_ref (label6);
  gtk_object_set_data_full (GTK_OBJECT (ConfDlg), "label6", label6,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label6);
  gtk_table_attach (GTK_TABLE (table2), label6, 1, 2, 6, 7,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label6), 0, 0.5);

  label4 = gtk_label_new (_("Second Controller"));
  gtk_widget_ref (label4);
  gtk_object_set_data_full (GTK_OBJECT (ConfDlg), "label4", label4,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label4);
  gtk_table_attach (GTK_TABLE (table2), label4, 1, 2, 3, 4,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label4), 0, 0.5);

  GtkCombo_Gpu = gtk_combo_new ();
  gtk_widget_ref (GtkCombo_Gpu);
  gtk_object_set_data_full (GTK_OBJECT (ConfDlg), "GtkCombo_Gpu", GtkCombo_Gpu,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (GtkCombo_Gpu);
  gtk_table_attach (GTK_TABLE (table2), GtkCombo_Gpu, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  combo_entry2 = GTK_COMBO (GtkCombo_Gpu)->entry;
  gtk_widget_ref (combo_entry2);
  gtk_object_set_data_full (GTK_OBJECT (ConfDlg), "combo_entry2", combo_entry2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (combo_entry2);

  GtkCombo_Spu = gtk_combo_new ();
  gtk_widget_ref (GtkCombo_Spu);
  gtk_object_set_data_full (GTK_OBJECT (ConfDlg), "GtkCombo_Spu", GtkCombo_Spu,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (GtkCombo_Spu);
  gtk_table_attach (GTK_TABLE (table2), GtkCombo_Spu, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  combo_entry3 = GTK_COMBO (GtkCombo_Spu)->entry;
  gtk_widget_ref (combo_entry3);
  gtk_object_set_data_full (GTK_OBJECT (ConfDlg), "combo_entry3", combo_entry3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (combo_entry3);

  hbox5 = gtk_hbox_new (FALSE, 14);
  gtk_widget_ref (hbox5);
  gtk_object_set_data_full (GTK_OBJECT (ConfDlg), "hbox5", hbox5,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox5);
  gtk_box_pack_start (GTK_BOX (vbox12), hbox5, TRUE, TRUE, 0);

  hbuttonbox11 = gtk_hbutton_box_new ();
  gtk_widget_ref (hbuttonbox11);
  gtk_object_set_data_full (GTK_OBJECT (ConfDlg), "hbuttonbox11", hbuttonbox11,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbuttonbox11);
  gtk_box_pack_start (GTK_BOX (hbox5), hbuttonbox11, TRUE, TRUE, 0);
  gtk_widget_set_usize (hbuttonbox11, 169, -2);
  gtk_button_box_set_spacing (GTK_BUTTON_BOX (hbuttonbox11), 0);

  button22 = gtk_button_new_with_label (_("Select Plugins Dir"));
  gtk_widget_ref (button22);
  gtk_object_set_data_full (GTK_OBJECT (ConfDlg), "button22", button22,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button22);
  gtk_container_add (GTK_CONTAINER (hbuttonbox11), button22);
  gtk_widget_set_usize (button22, 109, -2);
  GTK_WIDGET_SET_FLAGS (button22, GTK_CAN_DEFAULT);

  button23 = gtk_button_new_with_label (_("Select Bios Dir"));
  gtk_widget_ref (button23);
  gtk_object_set_data_full (GTK_OBJECT (ConfDlg), "button23", button23,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button23);
  gtk_container_add (GTK_CONTAINER (hbuttonbox11), button23);
  GTK_WIDGET_SET_FLAGS (button23, GTK_CAN_DEFAULT);

  hbuttonbox10 = gtk_hbutton_box_new ();
  gtk_widget_ref (hbuttonbox10);
  gtk_object_set_data_full (GTK_OBJECT (ConfDlg), "hbuttonbox10", hbuttonbox10,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbuttonbox10);
  gtk_box_pack_start (GTK_BOX (hbox5), hbuttonbox10, TRUE, TRUE, 0);
  gtk_button_box_set_spacing (GTK_BUTTON_BOX (hbuttonbox10), 0);

  button4 = gtk_button_new_with_label (_("Ok"));
  gtk_widget_ref (button4);
  gtk_object_set_data_full (GTK_OBJECT (ConfDlg), "button4", button4,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button4);
  gtk_container_add (GTK_CONTAINER (hbuttonbox10), button4);
  GTK_WIDGET_SET_FLAGS (button4, GTK_CAN_DEFAULT);

  button25 = gtk_button_new_with_label (_("Cancel"));
  gtk_widget_ref (button25);
  gtk_object_set_data_full (GTK_OBJECT (ConfDlg), "button25", button25,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button25);
  gtk_container_add (GTK_CONTAINER (hbuttonbox10), button25);
  GTK_WIDGET_SET_FLAGS (button25, GTK_CAN_DEFAULT);

  gtk_signal_connect (GTK_OBJECT (button6), "clicked",
                      GTK_SIGNAL_FUNC (OnConfConf_CdrConf),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (button7), "clicked",
                      GTK_SIGNAL_FUNC (OnConfConf_CdrTest),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (button8), "clicked",
                      GTK_SIGNAL_FUNC (OnConfConf_CdrAbout),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (button9), "clicked",
                      GTK_SIGNAL_FUNC (OnConfConf_Pad2Conf),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (button10), "clicked",
                      GTK_SIGNAL_FUNC (OnConfConf_Pad2Test),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (button11), "clicked",
                      GTK_SIGNAL_FUNC (OnConfConf_Pad2About),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (button12), "clicked",
                      GTK_SIGNAL_FUNC (OnConfConf_Pad1Conf),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (button13), "clicked",
                      GTK_SIGNAL_FUNC (OnConfConf_Pad1Test),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (button14), "clicked",
                      GTK_SIGNAL_FUNC (OnConfConf_Pad1About),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (button15), "clicked",
                      GTK_SIGNAL_FUNC (OnConfConf_GpuConf),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (button16), "clicked",
                      GTK_SIGNAL_FUNC (OnConfConf_GpuTest),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (button17), "clicked",
                      GTK_SIGNAL_FUNC (OnConfConf_GpuAbout),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (button18), "clicked",
                      GTK_SIGNAL_FUNC (OnConfConf_SpuConf),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (button19), "clicked",
                      GTK_SIGNAL_FUNC (OnConfConf_SpuTest),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (button20), "clicked",
                      GTK_SIGNAL_FUNC (OnConfConf_SpuAbout),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (button22), "clicked",
                      GTK_SIGNAL_FUNC (OnConfConf_PluginsPath),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (button23), "clicked",
                      GTK_SIGNAL_FUNC (OnConfConf_BiosPath),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (button4), "clicked",
                      GTK_SIGNAL_FUNC (OnConfConf_Ok),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (button25), "clicked",
                      GTK_SIGNAL_FUNC (OnConfConf_Cancel),
                      NULL);

  return ConfDlg;
}

GtkWidget*
create_CpuDlg (void)
{
  GtkWidget *CpuDlg;
  GtkWidget *vbox8;
  GtkWidget *frame3;
  GtkWidget *vbox15;
  GtkWidget *table1;
  GtkWidget *GtkCheckButton_Xa;
  GtkWidget *GtkCheckButton_Cdda;
  GtkWidget *GtkCheckButton_Sio;
  GtkWidget *GtkCheckButton_Cpu;
  GtkWidget *GtkCheckButton_PsxOut;
  GtkWidget *GtkCheckButton_Mdec;
  GtkWidget *GtkCheckButton_SpuIrq;
  GtkWidget *GtkCheckButton_RCntFix;
  GtkWidget *GtkCheckButton_VSyncWA;
  GtkWidget *frame6;
  GtkWidget *hbox4;
  GtkWidget *GtkCheckButton_PsxAuto;
  GtkWidget *GtkCombo_PsxType;
  GtkWidget *combo_entry1;
  GtkWidget *hbuttonbox3;
  GtkWidget *button2;
  GtkWidget *button3;

  CpuDlg = gtk_window_new (GTK_WINDOW_DIALOG);
  gtk_object_set_data (GTK_OBJECT (CpuDlg), "CpuDlg", CpuDlg);
  gtk_container_set_border_width (GTK_CONTAINER (CpuDlg), 5);
  gtk_window_set_title (GTK_WINDOW (CpuDlg), _("Cpu"));
  gtk_window_set_position (GTK_WINDOW (CpuDlg), GTK_WIN_POS_CENTER);
  gtk_window_set_policy (GTK_WINDOW (CpuDlg), FALSE, FALSE, FALSE);

  vbox8 = gtk_vbox_new (FALSE, 0);
  gtk_widget_ref (vbox8);
  gtk_object_set_data_full (GTK_OBJECT (CpuDlg), "vbox8", vbox8,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox8);
  gtk_container_add (GTK_CONTAINER (CpuDlg), vbox8);

  frame3 = gtk_frame_new (_("Options"));
  gtk_widget_ref (frame3);
  gtk_object_set_data_full (GTK_OBJECT (CpuDlg), "frame3", frame3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (frame3);
  gtk_box_pack_start (GTK_BOX (vbox8), frame3, TRUE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (frame3), 5);

  vbox15 = gtk_vbox_new (FALSE, 0);
  gtk_widget_ref (vbox15);
  gtk_object_set_data_full (GTK_OBJECT (CpuDlg), "vbox15", vbox15,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox15);
  gtk_container_add (GTK_CONTAINER (frame3), vbox15);
  gtk_container_set_border_width (GTK_CONTAINER (vbox15), 5);

  table1 = gtk_table_new (4, 2, FALSE);
  gtk_widget_ref (table1);
  gtk_object_set_data_full (GTK_OBJECT (CpuDlg), "table1", table1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (table1);
  gtk_box_pack_start (GTK_BOX (vbox15), table1, TRUE, TRUE, 0);

  GtkCheckButton_Xa = gtk_check_button_new_with_label (_("Disable Xa Decoding"));
  gtk_widget_ref (GtkCheckButton_Xa);
  gtk_object_set_data_full (GTK_OBJECT (CpuDlg), "GtkCheckButton_Xa", GtkCheckButton_Xa,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (GtkCheckButton_Xa);
  gtk_table_attach (GTK_TABLE (table1), GtkCheckButton_Xa, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  GtkCheckButton_Cdda = gtk_check_button_new_with_label (_("Disable Cd Audio"));
  gtk_widget_ref (GtkCheckButton_Cdda);
  gtk_object_set_data_full (GTK_OBJECT (CpuDlg), "GtkCheckButton_Cdda", GtkCheckButton_Cdda,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (GtkCheckButton_Cdda);
  gtk_table_attach (GTK_TABLE (table1), GtkCheckButton_Cdda, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  GtkCheckButton_Sio = gtk_check_button_new_with_label (_("Sio Irq Always Enabled"));
  gtk_widget_ref (GtkCheckButton_Sio);
  gtk_object_set_data_full (GTK_OBJECT (CpuDlg), "GtkCheckButton_Sio", GtkCheckButton_Sio,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (GtkCheckButton_Sio);
  gtk_table_attach (GTK_TABLE (table1), GtkCheckButton_Sio, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  GtkCheckButton_Cpu = gtk_check_button_new_with_label (_("Enable Interpreter Cpu"));
  gtk_widget_ref (GtkCheckButton_Cpu);
  gtk_object_set_data_full (GTK_OBJECT (CpuDlg), "GtkCheckButton_Cpu", GtkCheckButton_Cpu,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (GtkCheckButton_Cpu);
  gtk_table_attach (GTK_TABLE (table1), GtkCheckButton_Cpu, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  GtkCheckButton_PsxOut = gtk_check_button_new_with_label (_("Enable Console Output"));
  gtk_widget_ref (GtkCheckButton_PsxOut);
  gtk_object_set_data_full (GTK_OBJECT (CpuDlg), "GtkCheckButton_PsxOut", GtkCheckButton_PsxOut,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (GtkCheckButton_PsxOut);
  gtk_table_attach (GTK_TABLE (table1), GtkCheckButton_PsxOut, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  GtkCheckButton_Mdec = gtk_check_button_new_with_label (_("Black & White Movies"));
  gtk_widget_ref (GtkCheckButton_Mdec);
  gtk_object_set_data_full (GTK_OBJECT (CpuDlg), "GtkCheckButton_Mdec", GtkCheckButton_Mdec,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (GtkCheckButton_Mdec);
  gtk_table_attach (GTK_TABLE (table1), GtkCheckButton_Mdec, 0, 1, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  GtkCheckButton_SpuIrq = gtk_check_button_new_with_label (_("Spu Irq Always Enabled"));
  gtk_widget_ref (GtkCheckButton_SpuIrq);
  gtk_object_set_data_full (GTK_OBJECT (CpuDlg), "GtkCheckButton_SpuIrq", GtkCheckButton_SpuIrq,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (GtkCheckButton_SpuIrq);
  gtk_table_attach (GTK_TABLE (table1), GtkCheckButton_SpuIrq, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  GtkCheckButton_RCntFix = gtk_check_button_new_with_label (_("Parasite Eve 2, Vandal Hearts 1/2 Fix"));
  gtk_widget_ref (GtkCheckButton_RCntFix);
  gtk_object_set_data_full (GTK_OBJECT (CpuDlg), "GtkCheckButton_RCntFix", GtkCheckButton_RCntFix,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (GtkCheckButton_RCntFix);
  gtk_box_pack_start (GTK_BOX (vbox15), GtkCheckButton_RCntFix, FALSE, FALSE, 0);

  GtkCheckButton_VSyncWA = gtk_check_button_new_with_label (_("InuYasha Sengoku Battle Fix"));
  gtk_widget_ref (GtkCheckButton_VSyncWA);
  gtk_object_set_data_full (GTK_OBJECT (CpuDlg), "GtkCheckButton_VSyncWA", GtkCheckButton_VSyncWA,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (GtkCheckButton_VSyncWA);
  gtk_box_pack_start (GTK_BOX (vbox15), GtkCheckButton_VSyncWA, FALSE, FALSE, 0);

  frame6 = gtk_frame_new (_("Psx System Type"));
  gtk_widget_ref (frame6);
  gtk_object_set_data_full (GTK_OBJECT (CpuDlg), "frame6", frame6,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (frame6);
  gtk_box_pack_start (GTK_BOX (vbox8), frame6, TRUE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (frame6), 5);

  hbox4 = gtk_hbox_new (FALSE, 0);
  gtk_widget_ref (hbox4);
  gtk_object_set_data_full (GTK_OBJECT (CpuDlg), "hbox4", hbox4,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox4);
  gtk_container_add (GTK_CONTAINER (frame6), hbox4);
  gtk_container_set_border_width (GTK_CONTAINER (hbox4), 5);

  GtkCheckButton_PsxAuto = gtk_check_button_new_with_label (_("Autodetect"));
  gtk_widget_ref (GtkCheckButton_PsxAuto);
  gtk_object_set_data_full (GTK_OBJECT (CpuDlg), "GtkCheckButton_PsxAuto", GtkCheckButton_PsxAuto,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (GtkCheckButton_PsxAuto);
  gtk_box_pack_start (GTK_BOX (hbox4), GtkCheckButton_PsxAuto, FALSE, FALSE, 0);
  gtk_widget_set_usize (GtkCheckButton_PsxAuto, 159, -2);

  GtkCombo_PsxType = gtk_combo_new ();
  gtk_widget_ref (GtkCombo_PsxType);
  gtk_object_set_data_full (GTK_OBJECT (CpuDlg), "GtkCombo_PsxType", GtkCombo_PsxType,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (GtkCombo_PsxType);
  gtk_box_pack_start (GTK_BOX (hbox4), GtkCombo_PsxType, FALSE, FALSE, 0);
  gtk_widget_set_usize (GtkCombo_PsxType, 154, -2);

  combo_entry1 = GTK_COMBO (GtkCombo_PsxType)->entry;
  gtk_widget_ref (combo_entry1);
  gtk_object_set_data_full (GTK_OBJECT (CpuDlg), "combo_entry1", combo_entry1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (combo_entry1);
  gtk_entry_set_editable (GTK_ENTRY (combo_entry1), FALSE);

  hbuttonbox3 = gtk_hbutton_box_new ();
  gtk_widget_ref (hbuttonbox3);
  gtk_object_set_data_full (GTK_OBJECT (CpuDlg), "hbuttonbox3", hbuttonbox3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbuttonbox3);
  gtk_box_pack_start (GTK_BOX (vbox8), hbuttonbox3, TRUE, TRUE, 0);

  button2 = gtk_button_new_with_label (_("Ok"));
  gtk_widget_ref (button2);
  gtk_object_set_data_full (GTK_OBJECT (CpuDlg), "button2", button2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button2);
  gtk_container_add (GTK_CONTAINER (hbuttonbox3), button2);
  GTK_WIDGET_SET_FLAGS (button2, GTK_CAN_DEFAULT);

  button3 = gtk_button_new_with_label (_("Cancel"));
  gtk_widget_ref (button3);
  gtk_object_set_data_full (GTK_OBJECT (CpuDlg), "button3", button3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button3);
  gtk_container_add (GTK_CONTAINER (hbuttonbox3), button3);
  GTK_WIDGET_SET_FLAGS (button3, GTK_CAN_DEFAULT);

  gtk_signal_connect (GTK_OBJECT (button2), "clicked",
                      GTK_SIGNAL_FUNC (OnCpu_Ok),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (button3), "clicked",
                      GTK_SIGNAL_FUNC (OnCpu_Cancel),
                      NULL);

  return CpuDlg;
}

GtkWidget*
create_McdsDlg (void)
{
  GtkWidget *McdsDlg;
  GtkWidget *vbox10;
  GtkWidget *hbox6;
  GtkWidget *frame7;
  GtkWidget *vbox13;
  GtkWidget *scrolledwindow1;
  GtkWidget *GtkCList_McdList1;
  GtkWidget *label9;
  GtkWidget *label10;
  GtkWidget *label11;
  GtkWidget *label15;
  GtkWidget *label16;
  GtkWidget *hbuttonbox12;
  GtkWidget *GtkButton_SelMcd1;
  GtkWidget *GtkButton_Format1;
  GtkWidget *GtkButton_Reload1;
  GtkWidget *GtkEntry_Mcd1;
  GtkWidget *vbuttonbox1;
  GtkWidget *button26;
  GtkWidget *button28;
  GtkWidget *GtkButton_McdPaste;
  GtkWidget *button29;
  GtkWidget *button30;
  GtkWidget *frame8;
  GtkWidget *vbox14;
  GtkWidget *scrolledwindow2;
  GtkWidget *GtkCList_McdList2;
  GtkWidget *label12;
  GtkWidget *label13;
  GtkWidget *label14;
  GtkWidget *label17;
  GtkWidget *label18;
  GtkWidget *hbuttonbox13;
  GtkWidget *GtkButton_SelMcd2;
  GtkWidget *GtkButton_Format2;
  GtkWidget *GtkButton_Reload2;
  GtkWidget *GtkEntry_Mcd2;
  GtkWidget *hbuttonbox2;
  GtkWidget *GtkMcds_Ok;
  GtkWidget *GtkMcds_Cancel;

  McdsDlg = gtk_window_new (GTK_WINDOW_DIALOG);
  gtk_object_set_data (GTK_OBJECT (McdsDlg), "McdsDlg", McdsDlg);
  gtk_container_set_border_width (GTK_CONTAINER (McdsDlg), 5);
  gtk_window_set_title (GTK_WINDOW (McdsDlg), _("Mcds"));
  gtk_window_set_position (GTK_WINDOW (McdsDlg), GTK_WIN_POS_CENTER);

  vbox10 = gtk_vbox_new (FALSE, 5);
  gtk_widget_ref (vbox10);
  gtk_object_set_data_full (GTK_OBJECT (McdsDlg), "vbox10", vbox10,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox10);
  gtk_container_add (GTK_CONTAINER (McdsDlg), vbox10);

  hbox6 = gtk_hbox_new (FALSE, 0);
  gtk_widget_ref (hbox6);
  gtk_object_set_data_full (GTK_OBJECT (McdsDlg), "hbox6", hbox6,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox6);
  gtk_box_pack_start (GTK_BOX (vbox10), hbox6, TRUE, TRUE, 0);

  frame7 = gtk_frame_new (_("Memory Card 1"));
  gtk_widget_ref (frame7);
  gtk_object_set_data_full (GTK_OBJECT (McdsDlg), "frame7", frame7,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (frame7);
  gtk_box_pack_start (GTK_BOX (hbox6), frame7, TRUE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (frame7), 5);

  vbox13 = gtk_vbox_new (FALSE, 0);
  gtk_widget_ref (vbox13);
  gtk_object_set_data_full (GTK_OBJECT (McdsDlg), "vbox13", vbox13,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox13);
  gtk_container_add (GTK_CONTAINER (frame7), vbox13);
  gtk_container_set_border_width (GTK_CONTAINER (vbox13), 5);

  scrolledwindow1 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_ref (scrolledwindow1);
  gtk_object_set_data_full (GTK_OBJECT (McdsDlg), "scrolledwindow1", scrolledwindow1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (scrolledwindow1);
  gtk_box_pack_start (GTK_BOX (vbox13), scrolledwindow1, TRUE, TRUE, 0);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow1), GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);

  GtkCList_McdList1 = gtk_clist_new (5);
  gtk_widget_ref (GtkCList_McdList1);
  gtk_object_set_data_full (GTK_OBJECT (McdsDlg), "GtkCList_McdList1", GtkCList_McdList1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (GtkCList_McdList1);
  gtk_container_add (GTK_CONTAINER (scrolledwindow1), GtkCList_McdList1);
  gtk_widget_set_usize (GtkCList_McdList1, -2, 180);
  gtk_clist_set_column_width (GTK_CLIST (GtkCList_McdList1), 0, 25);
  gtk_clist_set_column_width (GTK_CLIST (GtkCList_McdList1), 1, 180);
  gtk_clist_set_column_width (GTK_CLIST (GtkCList_McdList1), 2, 50);
  gtk_clist_set_column_width (GTK_CLIST (GtkCList_McdList1), 3, 80);
  gtk_clist_set_column_width (GTK_CLIST (GtkCList_McdList1), 4, 80);
  gtk_clist_column_titles_show (GTK_CLIST (GtkCList_McdList1));

  label9 = gtk_label_new (_("Icon"));
  gtk_widget_ref (label9);
  gtk_object_set_data_full (GTK_OBJECT (McdsDlg), "label9", label9,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label9);
  gtk_clist_set_column_widget (GTK_CLIST (GtkCList_McdList1), 0, label9);

  label10 = gtk_label_new (_("Title"));
  gtk_widget_ref (label10);
  gtk_object_set_data_full (GTK_OBJECT (McdsDlg), "label10", label10,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label10);
  gtk_clist_set_column_widget (GTK_CLIST (GtkCList_McdList1), 1, label10);

  label11 = gtk_label_new (_("Status"));
  gtk_widget_ref (label11);
  gtk_object_set_data_full (GTK_OBJECT (McdsDlg), "label11", label11,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label11);
  gtk_clist_set_column_widget (GTK_CLIST (GtkCList_McdList1), 2, label11);

  label15 = gtk_label_new (_("Game ID"));
  gtk_widget_ref (label15);
  gtk_object_set_data_full (GTK_OBJECT (McdsDlg), "label15", label15,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label15);
  gtk_clist_set_column_widget (GTK_CLIST (GtkCList_McdList1), 3, label15);

  label16 = gtk_label_new (_("Game"));
  gtk_widget_ref (label16);
  gtk_object_set_data_full (GTK_OBJECT (McdsDlg), "label16", label16,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label16);
  gtk_clist_set_column_widget (GTK_CLIST (GtkCList_McdList1), 4, label16);

  hbuttonbox12 = gtk_hbutton_box_new ();
  gtk_widget_ref (hbuttonbox12);
  gtk_object_set_data_full (GTK_OBJECT (McdsDlg), "hbuttonbox12", hbuttonbox12,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbuttonbox12);
  gtk_box_pack_start (GTK_BOX (vbox13), hbuttonbox12, TRUE, TRUE, 0);
  gtk_widget_set_usize (hbuttonbox12, 240, -2);
  gtk_button_box_set_spacing (GTK_BUTTON_BOX (hbuttonbox12), 0);
  gtk_button_box_set_child_size (GTK_BUTTON_BOX (hbuttonbox12), 70, 27);

  GtkButton_SelMcd1 = gtk_button_new_with_label (_("Select"));
  gtk_widget_ref (GtkButton_SelMcd1);
  gtk_object_set_data_full (GTK_OBJECT (McdsDlg), "GtkButton_SelMcd1", GtkButton_SelMcd1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (GtkButton_SelMcd1);
  gtk_container_add (GTK_CONTAINER (hbuttonbox12), GtkButton_SelMcd1);
  GTK_WIDGET_SET_FLAGS (GtkButton_SelMcd1, GTK_CAN_DEFAULT);

  GtkButton_Format1 = gtk_button_new_with_label (_("Format"));
  gtk_widget_ref (GtkButton_Format1);
  gtk_object_set_data_full (GTK_OBJECT (McdsDlg), "GtkButton_Format1", GtkButton_Format1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (GtkButton_Format1);
  gtk_container_add (GTK_CONTAINER (hbuttonbox12), GtkButton_Format1);
  GTK_WIDGET_SET_FLAGS (GtkButton_Format1, GTK_CAN_DEFAULT);

  GtkButton_Reload1 = gtk_button_new_with_label (_("Reload"));
  gtk_widget_ref (GtkButton_Reload1);
  gtk_object_set_data_full (GTK_OBJECT (McdsDlg), "GtkButton_Reload1", GtkButton_Reload1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (GtkButton_Reload1);
  gtk_container_add (GTK_CONTAINER (hbuttonbox12), GtkButton_Reload1);
  GTK_WIDGET_SET_FLAGS (GtkButton_Reload1, GTK_CAN_DEFAULT);

  GtkEntry_Mcd1 = gtk_entry_new ();
  gtk_widget_ref (GtkEntry_Mcd1);
  gtk_object_set_data_full (GTK_OBJECT (McdsDlg), "GtkEntry_Mcd1", GtkEntry_Mcd1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (GtkEntry_Mcd1);
  gtk_box_pack_start (GTK_BOX (vbox13), GtkEntry_Mcd1, FALSE, FALSE, 0);

  vbuttonbox1 = gtk_vbutton_box_new ();
  gtk_widget_ref (vbuttonbox1);
  gtk_object_set_data_full (GTK_OBJECT (McdsDlg), "vbuttonbox1", vbuttonbox1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbuttonbox1);
  gtk_box_pack_start (GTK_BOX (hbox6), vbuttonbox1, TRUE, FALSE, 0);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (vbuttonbox1), GTK_BUTTONBOX_SPREAD);
  gtk_button_box_set_spacing (GTK_BUTTON_BOX (vbuttonbox1), 0);
  gtk_button_box_set_child_size (GTK_BUTTON_BOX (vbuttonbox1), 64, 27);
  gtk_button_box_set_child_ipadding (GTK_BUTTON_BOX (vbuttonbox1), 0, 0);

  button26 = gtk_button_new_with_label (_("-> Copy ->"));
  gtk_widget_ref (button26);
  gtk_object_set_data_full (GTK_OBJECT (McdsDlg), "button26", button26,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button26);
  gtk_container_add (GTK_CONTAINER (vbuttonbox1), button26);
  GTK_WIDGET_SET_FLAGS (button26, GTK_CAN_DEFAULT);

  button28 = gtk_button_new_with_label (_("<- Copy <-"));
  gtk_widget_ref (button28);
  gtk_object_set_data_full (GTK_OBJECT (McdsDlg), "button28", button28,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button28);
  gtk_container_add (GTK_CONTAINER (vbuttonbox1), button28);
  GTK_WIDGET_SET_FLAGS (button28, GTK_CAN_DEFAULT);

  GtkButton_McdPaste = gtk_button_new_with_label (_("Paste"));
  gtk_widget_ref (GtkButton_McdPaste);
  gtk_object_set_data_full (GTK_OBJECT (McdsDlg), "GtkButton_McdPaste", GtkButton_McdPaste,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (GtkButton_McdPaste);
  gtk_container_add (GTK_CONTAINER (vbuttonbox1), GtkButton_McdPaste);
  GTK_WIDGET_SET_FLAGS (GtkButton_McdPaste, GTK_CAN_DEFAULT);

  button29 = gtk_button_new_with_label (_("Un/Delete ->"));
  gtk_widget_ref (button29);
  gtk_object_set_data_full (GTK_OBJECT (McdsDlg), "button29", button29,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button29);
  gtk_container_add (GTK_CONTAINER (vbuttonbox1), button29);
  GTK_WIDGET_SET_FLAGS (button29, GTK_CAN_DEFAULT);

  button30 = gtk_button_new_with_label (_("<- Un/Delete"));
  gtk_widget_ref (button30);
  gtk_object_set_data_full (GTK_OBJECT (McdsDlg), "button30", button30,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button30);
  gtk_container_add (GTK_CONTAINER (vbuttonbox1), button30);
  GTK_WIDGET_SET_FLAGS (button30, GTK_CAN_DEFAULT);

  frame8 = gtk_frame_new (_("Memory Card 2"));
  gtk_widget_ref (frame8);
  gtk_object_set_data_full (GTK_OBJECT (McdsDlg), "frame8", frame8,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (frame8);
  gtk_box_pack_start (GTK_BOX (hbox6), frame8, TRUE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (frame8), 5);

  vbox14 = gtk_vbox_new (FALSE, 0);
  gtk_widget_ref (vbox14);
  gtk_object_set_data_full (GTK_OBJECT (McdsDlg), "vbox14", vbox14,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox14);
  gtk_container_add (GTK_CONTAINER (frame8), vbox14);
  gtk_container_set_border_width (GTK_CONTAINER (vbox14), 5);

  scrolledwindow2 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_ref (scrolledwindow2);
  gtk_object_set_data_full (GTK_OBJECT (McdsDlg), "scrolledwindow2", scrolledwindow2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (scrolledwindow2);
  gtk_box_pack_start (GTK_BOX (vbox14), scrolledwindow2, TRUE, TRUE, 0);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow2), GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);

  GtkCList_McdList2 = gtk_clist_new (5);
  gtk_widget_ref (GtkCList_McdList2);
  gtk_object_set_data_full (GTK_OBJECT (McdsDlg), "GtkCList_McdList2", GtkCList_McdList2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (GtkCList_McdList2);
  gtk_container_add (GTK_CONTAINER (scrolledwindow2), GtkCList_McdList2);
  gtk_widget_set_usize (GtkCList_McdList2, -2, 180);
  gtk_clist_set_column_width (GTK_CLIST (GtkCList_McdList2), 0, 25);
  gtk_clist_set_column_width (GTK_CLIST (GtkCList_McdList2), 1, 180);
  gtk_clist_set_column_width (GTK_CLIST (GtkCList_McdList2), 2, 50);
  gtk_clist_set_column_width (GTK_CLIST (GtkCList_McdList2), 3, 80);
  gtk_clist_set_column_width (GTK_CLIST (GtkCList_McdList2), 4, 80);
  gtk_clist_column_titles_show (GTK_CLIST (GtkCList_McdList2));

  label12 = gtk_label_new (_("Icon"));
  gtk_widget_ref (label12);
  gtk_object_set_data_full (GTK_OBJECT (McdsDlg), "label12", label12,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label12);
  gtk_clist_set_column_widget (GTK_CLIST (GtkCList_McdList2), 0, label12);

  label13 = gtk_label_new (_("Title"));
  gtk_widget_ref (label13);
  gtk_object_set_data_full (GTK_OBJECT (McdsDlg), "label13", label13,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label13);
  gtk_clist_set_column_widget (GTK_CLIST (GtkCList_McdList2), 1, label13);

  label14 = gtk_label_new (_("Status"));
  gtk_widget_ref (label14);
  gtk_object_set_data_full (GTK_OBJECT (McdsDlg), "label14", label14,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label14);
  gtk_clist_set_column_widget (GTK_CLIST (GtkCList_McdList2), 2, label14);

  label17 = gtk_label_new (_("Game ID"));
  gtk_widget_ref (label17);
  gtk_object_set_data_full (GTK_OBJECT (McdsDlg), "label17", label17,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label17);
  gtk_clist_set_column_widget (GTK_CLIST (GtkCList_McdList2), 3, label17);

  label18 = gtk_label_new (_("Game"));
  gtk_widget_ref (label18);
  gtk_object_set_data_full (GTK_OBJECT (McdsDlg), "label18", label18,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label18);
  gtk_clist_set_column_widget (GTK_CLIST (GtkCList_McdList2), 4, label18);

  hbuttonbox13 = gtk_hbutton_box_new ();
  gtk_widget_ref (hbuttonbox13);
  gtk_object_set_data_full (GTK_OBJECT (McdsDlg), "hbuttonbox13", hbuttonbox13,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbuttonbox13);
  gtk_box_pack_start (GTK_BOX (vbox14), hbuttonbox13, TRUE, TRUE, 0);
  gtk_widget_set_usize (hbuttonbox13, 240, -2);
  gtk_button_box_set_spacing (GTK_BUTTON_BOX (hbuttonbox13), 0);
  gtk_button_box_set_child_size (GTK_BUTTON_BOX (hbuttonbox13), 70, 27);

  GtkButton_SelMcd2 = gtk_button_new_with_label (_("Select"));
  gtk_widget_ref (GtkButton_SelMcd2);
  gtk_object_set_data_full (GTK_OBJECT (McdsDlg), "GtkButton_SelMcd2", GtkButton_SelMcd2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (GtkButton_SelMcd2);
  gtk_container_add (GTK_CONTAINER (hbuttonbox13), GtkButton_SelMcd2);
  GTK_WIDGET_SET_FLAGS (GtkButton_SelMcd2, GTK_CAN_DEFAULT);

  GtkButton_Format2 = gtk_button_new_with_label (_("Format"));
  gtk_widget_ref (GtkButton_Format2);
  gtk_object_set_data_full (GTK_OBJECT (McdsDlg), "GtkButton_Format2", GtkButton_Format2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (GtkButton_Format2);
  gtk_container_add (GTK_CONTAINER (hbuttonbox13), GtkButton_Format2);
  GTK_WIDGET_SET_FLAGS (GtkButton_Format2, GTK_CAN_DEFAULT);

  GtkButton_Reload2 = gtk_button_new_with_label (_("Reload"));
  gtk_widget_ref (GtkButton_Reload2);
  gtk_object_set_data_full (GTK_OBJECT (McdsDlg), "GtkButton_Reload2", GtkButton_Reload2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (GtkButton_Reload2);
  gtk_container_add (GTK_CONTAINER (hbuttonbox13), GtkButton_Reload2);
  GTK_WIDGET_SET_FLAGS (GtkButton_Reload2, GTK_CAN_DEFAULT);

  GtkEntry_Mcd2 = gtk_entry_new ();
  gtk_widget_ref (GtkEntry_Mcd2);
  gtk_object_set_data_full (GTK_OBJECT (McdsDlg), "GtkEntry_Mcd2", GtkEntry_Mcd2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (GtkEntry_Mcd2);
  gtk_box_pack_start (GTK_BOX (vbox14), GtkEntry_Mcd2, FALSE, FALSE, 0);

  hbuttonbox2 = gtk_hbutton_box_new ();
  gtk_widget_ref (hbuttonbox2);
  gtk_object_set_data_full (GTK_OBJECT (McdsDlg), "hbuttonbox2", hbuttonbox2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbuttonbox2);
  gtk_box_pack_start (GTK_BOX (vbox10), hbuttonbox2, TRUE, TRUE, 0);

  GtkMcds_Ok = gtk_button_new_with_label (_("Ok"));
  gtk_widget_ref (GtkMcds_Ok);
  gtk_object_set_data_full (GTK_OBJECT (McdsDlg), "GtkMcds_Ok", GtkMcds_Ok,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (GtkMcds_Ok);
  gtk_container_add (GTK_CONTAINER (hbuttonbox2), GtkMcds_Ok);
  GTK_WIDGET_SET_FLAGS (GtkMcds_Ok, GTK_CAN_DEFAULT);

  GtkMcds_Cancel = gtk_button_new_with_label (_("Cancel"));
  gtk_widget_ref (GtkMcds_Cancel);
  gtk_object_set_data_full (GTK_OBJECT (McdsDlg), "GtkMcds_Cancel", GtkMcds_Cancel,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (GtkMcds_Cancel);
  gtk_container_add (GTK_CONTAINER (hbuttonbox2), GtkMcds_Cancel);
  GTK_WIDGET_SET_FLAGS (GtkMcds_Cancel, GTK_CAN_DEFAULT);

  gtk_signal_connect (GTK_OBJECT (GtkButton_SelMcd1), "clicked",
                      GTK_SIGNAL_FUNC (OnMcd_FS1),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (GtkButton_Format1), "clicked",
                      GTK_SIGNAL_FUNC (OnMcd_Format1),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (GtkButton_Reload1), "clicked",
                      GTK_SIGNAL_FUNC (OnMcd_Reload1),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (button26), "clicked",
                      GTK_SIGNAL_FUNC (OnMcd_CopyTo2),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (button28), "clicked",
                      GTK_SIGNAL_FUNC (OnMcd_CopyTo1),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (GtkButton_McdPaste), "clicked",
                      GTK_SIGNAL_FUNC (OnMcd_Paste),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (button29), "clicked",
                      GTK_SIGNAL_FUNC (OnMcd_Delete2),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (button30), "clicked",
                      GTK_SIGNAL_FUNC (OnMcd_Delete1),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (GtkButton_SelMcd2), "clicked",
                      GTK_SIGNAL_FUNC (OnMcd_FS2),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (GtkButton_Format2), "clicked",
                      GTK_SIGNAL_FUNC (OnMcd_Format2),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (GtkButton_Reload2), "clicked",
                      GTK_SIGNAL_FUNC (OnMcd_Reload2),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (GtkMcds_Ok), "clicked",
                      GTK_SIGNAL_FUNC (OnMcd_Ok),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (GtkMcds_Cancel), "clicked",
                      GTK_SIGNAL_FUNC (OnMcd_Cancel),
                      NULL);

  return McdsDlg;
}

GtkWidget*
create_NetDlg (void)
{
  GtkWidget *NetDlg;
  GtkWidget *vbox16;
  GtkWidget *vbox17;
  GtkWidget *label19;
  GtkWidget *GtkCombo_Net;
  GtkWidget *entry1;
  GtkWidget *hbuttonbox15;
  GtkWidget *button33;
  GtkWidget *button34;
  GtkWidget *button35;
  GtkWidget *hbuttonbox14;
  GtkWidget *button31;
  GtkWidget *button32;

  NetDlg = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_object_set_data (GTK_OBJECT (NetDlg), "NetDlg", NetDlg);
  gtk_container_set_border_width (GTK_CONTAINER (NetDlg), 10);
  gtk_window_set_title (GTK_WINDOW (NetDlg), _("NetPlay Configuration"));
  gtk_window_set_position (GTK_WINDOW (NetDlg), GTK_WIN_POS_CENTER);

  vbox16 = gtk_vbox_new (FALSE, 0);
  gtk_widget_ref (vbox16);
  gtk_object_set_data_full (GTK_OBJECT (NetDlg), "vbox16", vbox16,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox16);
  gtk_container_add (GTK_CONTAINER (NetDlg), vbox16);

  vbox17 = gtk_vbox_new (FALSE, 0);
  gtk_widget_ref (vbox17);
  gtk_object_set_data_full (GTK_OBJECT (NetDlg), "vbox17", vbox17,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox17);
  gtk_box_pack_start (GTK_BOX (vbox16), vbox17, TRUE, TRUE, 0);

  label19 = gtk_label_new (_("NetPlay"));
  gtk_widget_ref (label19);
  gtk_object_set_data_full (GTK_OBJECT (NetDlg), "label19", label19,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label19);
  gtk_box_pack_start (GTK_BOX (vbox17), label19, FALSE, FALSE, 0);

  GtkCombo_Net = gtk_combo_new ();
  gtk_widget_ref (GtkCombo_Net);
  gtk_object_set_data_full (GTK_OBJECT (NetDlg), "GtkCombo_Net", GtkCombo_Net,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (GtkCombo_Net);
  gtk_box_pack_start (GTK_BOX (vbox17), GtkCombo_Net, FALSE, FALSE, 0);

  entry1 = GTK_COMBO (GtkCombo_Net)->entry;
  gtk_widget_ref (entry1);
  gtk_object_set_data_full (GTK_OBJECT (NetDlg), "entry1", entry1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (entry1);

  hbuttonbox15 = gtk_hbutton_box_new ();
  gtk_widget_ref (hbuttonbox15);
  gtk_object_set_data_full (GTK_OBJECT (NetDlg), "hbuttonbox15", hbuttonbox15,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbuttonbox15);
  gtk_box_pack_start (GTK_BOX (vbox17), hbuttonbox15, TRUE, TRUE, 0);
  gtk_button_box_set_spacing (GTK_BUTTON_BOX (hbuttonbox15), 0);

  button33 = gtk_button_new_with_label (_("Configure"));
  gtk_widget_ref (button33);
  gtk_object_set_data_full (GTK_OBJECT (NetDlg), "button33", button33,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button33);
  gtk_container_add (GTK_CONTAINER (hbuttonbox15), button33);
  GTK_WIDGET_SET_FLAGS (button33, GTK_CAN_DEFAULT);

  button34 = gtk_button_new_with_label (_("Test"));
  gtk_widget_ref (button34);
  gtk_object_set_data_full (GTK_OBJECT (NetDlg), "button34", button34,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button34);
  gtk_container_add (GTK_CONTAINER (hbuttonbox15), button34);
  GTK_WIDGET_SET_FLAGS (button34, GTK_CAN_DEFAULT);

  button35 = gtk_button_new_with_label (_("About"));
  gtk_widget_ref (button35);
  gtk_object_set_data_full (GTK_OBJECT (NetDlg), "button35", button35,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button35);
  gtk_container_add (GTK_CONTAINER (hbuttonbox15), button35);
  GTK_WIDGET_SET_FLAGS (button35, GTK_CAN_DEFAULT);

  hbuttonbox14 = gtk_hbutton_box_new ();
  gtk_widget_ref (hbuttonbox14);
  gtk_object_set_data_full (GTK_OBJECT (NetDlg), "hbuttonbox14", hbuttonbox14,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbuttonbox14);
  gtk_box_pack_start (GTK_BOX (vbox16), hbuttonbox14, TRUE, TRUE, 0);

  button31 = gtk_button_new_with_label (_("Ok"));
  gtk_widget_ref (button31);
  gtk_object_set_data_full (GTK_OBJECT (NetDlg), "button31", button31,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button31);
  gtk_container_add (GTK_CONTAINER (hbuttonbox14), button31);
  GTK_WIDGET_SET_FLAGS (button31, GTK_CAN_DEFAULT);

  button32 = gtk_button_new_with_label (_("Cancel"));
  gtk_widget_ref (button32);
  gtk_object_set_data_full (GTK_OBJECT (NetDlg), "button32", button32,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button32);
  gtk_container_add (GTK_CONTAINER (hbuttonbox14), button32);
  GTK_WIDGET_SET_FLAGS (button32, GTK_CAN_DEFAULT);

  gtk_signal_connect (GTK_OBJECT (button33), "clicked",
                      GTK_SIGNAL_FUNC (OnNet_Conf),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (button34), "clicked",
                      GTK_SIGNAL_FUNC (OnNet_Test),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (button35), "clicked",
                      GTK_SIGNAL_FUNC (OnNet_About),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (button31), "clicked",
                      GTK_SIGNAL_FUNC (OnNet_Ok),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (button32), "clicked",
                      GTK_SIGNAL_FUNC (OnNet_Cancel),
                      NULL);

  return NetDlg;
}

