/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_MainWindow (void);
GtkWidget* create_AboutDlg (void);
GtkWidget* create_ConfDlg (void);
GtkWidget* create_CpuDlg (void);
GtkWidget* create_McdsDlg (void);
GtkWidget* create_NetDlg (void);
